# Generated by Django 5.1.2 on 2024-10-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/media/image/default_image.png', upload_to='images/'),
        ),
    ]
