# Generated by Django 5.1.2 on 2024-10-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_caraction_delete_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="caraction",
            name="garage",
            field=models.CharField(
                choices=[("A", "Garagem VIP"), ("B", "Garagem CIMATEC PARK")],
                default="A",
                max_length=1,
            ),
        ),
    ]
