# Generated by Django 5.2.2 on 2025-06-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_caraction_garage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caraction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Movimentação de Carro', 'verbose_name_plural': 'Movimentações de Carros'},
        ),
        migrations.AlterField(
            model_name='caraction',
            name='action',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=7, verbose_name='Tipo de Ação'),
        ),
        migrations.AlterField(
            model_name='caraction',
            name='garage',
            field=models.CharField(choices=[('A', 'Garagem VIP'), ('B', 'Garagem CIMATEC PARK')], default='A', max_length=1, verbose_name='Garagem'),
        ),
        migrations.AlterField(
            model_name='caraction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora'),
        ),
    ]
